"""Re-fit how far to trust the NFL yardage model over the bookmaker's price.

Reads the graded props in data-raw/nfl/picks_log.json and writes
data-raw/nfl/blend_weights.json (see nfl/market_blend.py). Runs before every NFL
publish, so the weight follows the record as book-line picks are graded.
"""
import json
import sys
from datetime import datetime, timezone

from nfl import market_blend as mb


def main() -> int:
    try:
        log = json.loads((mb.ROOT / "data-raw" / "nfl" / "picks_log.json")
                         .read_text(encoding="utf-8")).get("props") or {}
    except Exception as exc:
        print(f"no picks log ({exc}); keeping the existing weights")
        return 0
    result = mb.fit_all(log)
    result["updated"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
    result["_note"] = ("p = book + w * (model - book), w fitted by maximum likelihood on "
                       "graded yardage picks (nfl/market_blend.py). Generated by "
                       "scripts/fit_nfl_blend.py -- never hand-edit.")
    mb.WEIGHTS.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    for m in mb.YARDAGE:
        r = result[m]
        print(f"  {m}: w={r['w_used']} ({r['source']}, {r['n']} graded, "
              f"hit {r.get('hit_rate')} vs raw model {r.get('raw_model_mean')})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
