"""Fit nfl/vacancy.py's correction on out-of-sample walk-forward predictions.

Writes data-raw/nfl/vacancy_adjust.json: per market, c and the evidence -- the
season-by-season Brier with and without it, where each season's c was fitted only
on seasons before it, and the calibration in the 20%+ vacated bucket. A market is
given a non-zero c only when the correction lowered Brier across the walk-forward
seasons as a whole; otherwise c is 0 and nothing changes.
"""
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.optimize import minimize_scalar

from nfl import backtest, data, features, vacancy

ROOT = Path(__file__).resolve().parents[1]


def _fit(df) -> float:
    z = np.log(np.clip(df["prob"], 1e-4, 1 - 1e-4) / (1 - np.clip(df["prob"], 1e-4, 1 - 1e-4)))
    b, y = df["boost"].to_numpy(), df["outcome"].to_numpy()

    def loss(c):
        q = np.clip(1 / (1 + np.exp(-(z + c * b))), 1e-6, 1 - 1e-6)
        return -np.mean(y * np.log(q) + (1 - y) * np.log(1 - q))
    return float(minimize_scalar(loss, bounds=(0.0, 10.0), method="bounded").x)


def _brier(p, y):
    return round(float(np.mean((np.asarray(p) - np.asarray(y)) ** 2)), 6)


MIN_HIGH_VACANCY = 100   # games with 20%+ vacated before a correction may apply


def main():
    # PRE-GAME ABSENCES ONLY (data.known_out): an absence counts only if the
    # official injury report listed the player Out or Doubtful before kickoff.
    # Reading absence from the box score let late scratches -- which nobody
    # could bet on -- flatter the backtest; with them removed (2026-10-02) the
    # receiving and rushing corrections stopped paying and are switched off.
    features.KNOWN_OUT = data.known_out()
    pw, games = data.player_weeks(), data.games()
    report = {"_note": ("Phase 3 vacancy correction (nfl/vacancy.py). Generated by "
                        "scripts/fit_nfl_vacancy.py -- do not hand-edit."),
              "markets": {}}
    for market in vacancy.MARKETS:
        frame = features.build(pw, market, games=games)
        wf = backtest.walk_forward(frame, market)
        extra = frame[["player_id", "season", "week", "vacated", "form5"]].drop_duplicates(
            ["player_id", "season", "week"])
        wf = wf.merge(extra, on=["player_id", "season", "week"], how="left")
        wf["boost"] = vacancy.boost(wf["form5"].fillna(0), wf["vacated"].fillna(0), wf["line"])
        seasons = sorted(wf["season"].unique())
        scored = []
        for s in seasons[1:]:
            c = _fit(wf[wf["season"] < s])
            t = wf[wf["season"] == s].copy()
            t["adj"] = vacancy.adjust(t["prob"], t["form5"].fillna(0), t["vacated"].fillna(0), t["line"], c)
            t["c"] = c
            scored.append(t)
        a = pd.concat(scored)
        by_season = {int(s): {"base": _brier(g["prob"], g["outcome"]),
                              "adjusted": _brier(g["adj"], g["outcome"]), "c": round(float(g["c"].iloc[0]), 3)}
                     for s, g in a.groupby("season")}
        hi_all = a[a["vacated"].fillna(0) >= 0.20]
        n_hi = len(hi_all[hi_all["line_mult"] == 1.0]) if "line_mult" in hi_all.columns else len(hi_all)
        helps = (_brier(a["adj"], a["outcome"]) < _brier(a["prob"], a["outcome"])
                 and n_hi >= MIN_HIGH_VACANCY)
        c_all = _fit(wf) if helps else 0.0
        hi = a[a["vacated"].fillna(0) >= 0.20]
        main_rows = hi[hi["line_mult"] == 1.0] if "line_mult" in hi.columns else hi
        report["markets"][market] = {
            "c": round(c_all, 3), "applied": bool(helps),
            "brier": {"base": _brier(a["prob"], a["outcome"]), "adjusted": _brier(a["adj"], a["outcome"])},
            "by_season": by_season,
            "vacated_20pct_plus": {"n": int(len(main_rows)),
                                   "predicted": round(float(main_rows["prob"].mean()), 4) if len(main_rows) else None,
                                   "adjusted": round(float(main_rows["adj"].mean()), 4) if len(main_rows) else None,
                                   "landed": round(float(main_rows["outcome"].mean()), 4) if len(main_rows) else None}}
        print(market, json.dumps(report["markets"][market]))
    vacancy.PATH.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {vacancy.PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
