"""Measure whether the pick locker ACTUALLY runs, before trusting that it does.

`LOCK_WINDOW_HOURS` is only safe to narrow if a locker run reliably happens
inside the narrowed window. That is an empirical claim about GitHub's scheduler,
not a design decision, so it gets measured rather than assumed -- the same reason
the late-lock problem was diagnosed by counting real run delays instead of
trusting the cron.

Run: python -m scripts.measure_lock_reliability   (needs the `gh` CLI, read-only)
"""
import json
import subprocess
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data-raw" / "lock_reliability.json"
ACTIVE_HOURS = range(11, 24)          # the hours lock.yml's cron covers
SLOT_MINUTES = 10


def _t(stamp: str) -> datetime:
    return datetime.fromisoformat(stamp.replace("Z", "+00:00"))


def fetch_all_scheduled() -> list:
    """Every scheduled run in the repo, any workflow.

    THE NUMBER THAT TURNED OUT TO MATTER. Measuring lock.yml alone showed a 3.1%
    fire rate and suggested GitHub was dropping one high-frequency cron. The
    repo-wide count showed something worse: total scheduled runs fell from ~30 a
    day to 3-7 on the day lock.yml was added, and leagues.yml -- which both
    publishes the boards and freezes their picks -- fell from 27-28 a day to 4.
    The new workflow did not add capacity, it competed for it.

    So this is tracked repo-wide from now on. A per-workflow rate cannot see a
    budget being shared, and it is the shared budget that decides whether a pick
    gets frozen before kickoff.
    """
    proc = subprocess.run(
        ["gh", "run", "list", "--limit", "1000",
         "--json", "workflowName,event,createdAt,conclusion"],
        capture_output=True, text=True, cwd=ROOT)
    if proc.returncode:
        raise SystemExit(f"gh failed: {proc.stderr.strip()}")
    return [r for r in json.loads(proc.stdout) if r["event"] == "schedule"]


def per_day(runs: list) -> dict:
    """date -> {workflow: count}, newest last."""
    out = {}
    for run in runs:
        day = _t(run["createdAt"]).date().isoformat()
        out.setdefault(day, {})
        name = run["workflowName"]
        out[day][name] = out[day].get(name, 0) + 1
    return dict(sorted(out.items()))


def fetch() -> list:
    proc = subprocess.run(
        ["gh", "run", "list", "--workflow=lock.yml", "--limit", "300",
         "--json", "conclusion,createdAt,event"],
        capture_output=True, text=True, cwd=ROOT)
    if proc.returncode:
        raise SystemExit(f"gh failed: {proc.stderr.strip()}")
    return [r for r in json.loads(proc.stdout) if r["event"] == "schedule"]


def measure(runs: list, now=None) -> dict:
    now = now or datetime.now(timezone.utc)
    runs = sorted(runs, key=lambda r: r["createdAt"])
    if not runs:
        return {"error": "no scheduled runs recorded"}
    fired = [_t(r["createdAt"]) for r in runs]
    first = fired[0]

    # How many cron slots were DUE in the observed span.
    due, slot = 0, first.replace(minute=(first.minute // SLOT_MINUTES) * SLOT_MINUTES,
                                 second=0, microsecond=0)
    while slot <= now:
        if slot.hour in ACTIVE_HOURS:
            due += 1
        slot += timedelta(minutes=SLOT_MINUTES)

    # THE NUMBER THAT DECIDES THE WINDOW: the longest the locker was absent. A
    # pick can only freeze when a run happens, so the window must be at least
    # this wide or a pick inside it never freezes before kickoff.
    edges = [first] + fired[1:] + [now]
    worst = max((b - a).total_seconds() / 3600 for a, b in zip(edges, edges[1:]))

    return {
        "measured_at": now.isoformat(),
        "observed_from": first.isoformat(),
        "observed_hours": round((now - first).total_seconds() / 3600, 1),
        "slots_due": due,
        "runs_fired": len(fired),
        "fire_rate_pct": round(100 * len(fired) / due, 1) if due else None,
        "fired_outside_active_hours": sum(
            1 for t in fired if t.hour not in ACTIVE_HOURS),
        "failures": sum(1 for r in runs if r["conclusion"] != "success"),
        "worst_gap_hours": round(worst, 1),
        "safe_lock_window_hours": round(worst, 1),
        "_note": ("Generated by scripts/measure_lock_reliability.py -- do not "
                  "hand-edit. `worst_gap_hours` is the floor for "
                  "LOCK_WINDOW_HOURS: narrower than this and a pick can reach "
                  "kickoff with no locker run having happened."),
    }


def main() -> int:
    result = measure(fetch())
    days = per_day(fetch_all_scheduled())
    result["scheduled_runs_per_day"] = days
    recent = list(days.items())[-7:]
    result["repo_wide_note"] = (
        "Total scheduled runs across ALL workflows. lock.yml's own `*/10` cron "
        "was removed on 2026-08-29 after this collapsed from ~30/day to 3-7/day "
        "the day it was added; locking now rides leagues.yml as a fast job.")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    if "error" in result:
        print(result["error"])
        return 0
    print(f"observed {result['observed_hours']}h: {result['runs_fired']} of "
          f"{result['slots_due']} cron slots fired "
          f"({result['fire_rate_pct']}%), {result['failures']} failed")
    print(f"longest gap with no locker: {result['worst_gap_hours']}h")
    print(f"=> LOCK_WINDOW_HOURS must be at least {result['worst_gap_hours']}")
    print()
    print("scheduled runs per day, ALL workflows:")
    for day, counts in recent:
        detail = "  ".join(f"{k.split()[0]}={v}" for k, v in sorted(counts.items()))
        print(f"  {day}  total {sum(counts.values()):3d}   {detail}")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
