"""Run the MLB gate: 19 seasons loaded, 15 scored (2011-2025), every market.

Writes data-raw/mlb/backtest_report.json after EACH market, so a long run's
finished markets are never lost. `--only hits,strikeouts` runs a subset and
keeps the other markets' previous results.
"""
import json
import sys
import time
from pathlib import Path

from mlb import backtest, config, data, features

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data-raw" / "mlb" / "backtest_report.json"


def save(report):
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")


def main() -> int:
    only = None
    if "--only" in sys.argv:
        only = set(sys.argv[sys.argv.index("--only") + 1].split(","))
    try:
        report = json.loads(OUT.read_text(encoding="utf-8"))
    except Exception:
        report = {}
    report.update({"seasons_loaded": list(config.SEASONS),
                   "seasons_scored": list(config.SCORED_SEASONS),
                   "_note": ("Walk-forward MLB backtest (Retrosheet game logs). Every "
                             "scored season is one the model never saw. Generated by "
                             "scripts/mlb_backtest.py -- do not hand-edit.")})
    markets = report.setdefault("markets", {})

    if only is None or "team_winner" in only:
        t0 = time.time()
        result, params = backtest.team_winner(data.games())
        markets["team_winner"] = result
        save(report)
        print(f"team_winner n={result['n']} acc {result['accuracy']} brier {result['brier']} "
              f"vs home field {result['baseline_brier']} RELEASED={result['released']} "
              f"params {params} ({time.time()-t0:.0f}s)", flush=True)
        if result["failures"]:
            print(f"   withheld: {result['failures'][:4]}", flush=True)

    sources = {"batter": data.batter_games, "pitcher": data.pitcher_games,
               "team": data.team_games}
    loaded = {}
    for market, spec in config.MARKETS.items():
        if only is not None and market not in only:
            continue
        t0 = time.time()
        kind = spec["kind"]
        if kind not in loaded:
            loaded[kind] = sources[kind]()
        frame = features.augment_lines(features.build(loaded[kind], market), market)
        print(f"{market}: {len(frame)} rows across the line spread", flush=True)
        result = backtest.evaluate(backtest.walk_forward(frame, market), market)
        markets[market] = result
        save(report)
        print(f"{market} n={result['n']} acc {result['accuracy']} brier {result['brier']} "
              f"vs {result['baseline_brier']} ECE {result['ece']} "
              f"RELEASED={result['released']} ({time.time()-t0:.0f}s)", flush=True)
        for step, s in (result.get("by_line_step") or {}).items():
            print(f"   step {int(step):+d}: n={s['n']} predicted {s['predicted']} "
                  f"landed {s['landed']} ECE {s['ece']}", flush=True)
        if result["failures"]:
            print(f"   withheld: {result['failures'][:4]}", flush=True)
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
