"""Run the NBA gate over fifteen seasons and write the report."""
import json
import sys
from pathlib import Path

from nba import backtest, config, data, features, games_backtest

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data-raw" / "nba" / "backtest_report.json"


def main():
    seasons = list(config.SEASONS)
    print(f"loading {len(seasons)} seasons: {seasons[0]}-{seasons[-1]} "
          f"({data.season_label(seasons[0])} to {data.season_label(seasons[-1])})")

    report = {"seasons_loaded": seasons,
              "seasons_scored": seasons[config.BURN_IN_SEASONS:],
              "markets": {}}

    if "--props-only" not in sys.argv:
        games = data.games(seasons)
        print(f"team games: {len(games)} ({int(games['neutral'].sum())} neutral venue)")
        team = games_backtest.evaluate(games_backtest.walk_forward(games))
        report["markets"]["team_winner"] = team
        print(f"  team_winner  n={team['n']:6d}  brier {team['brier']}  "
              f"vs home court {team['baseline_brier']}  acc {team['accuracy']}  "
              f"RELEASED={team['released']}")
        if team.get("failures"):
            print(f"     withheld because: {team['failures'][:3]}")
    else:
        # Keep the team-winner result already on disk rather than recomputing a
        # 240-combination Elo grid search that takes the better part of an hour.
        try:
            old = json.loads(OUT.read_text(encoding="utf-8"))
            report["markets"]["team_winner"] = old["markets"]["team_winner"]
            print("team_winner: reused from the existing report (--props-only)")
        except Exception:
            print("team_winner: no previous result to reuse")

    player = data.player_games(seasons)
    print(f"player rows: {len(player)}")
    for market in config.MARKETS:
        frame = features.build(player, market)
        result = backtest.evaluate(backtest.walk_forward(frame, market), market)
        report["markets"][market] = result
        print(f"  {market:11s}  n={result['n']:6d}  brier {result['brier']}  "
              f"vs baseline {result['baseline_brier']}  acc {result['accuracy']}  "
              f"ECE {result['ece']}  floor {result['floor_share']:.0%}  "
              f"RELEASED={result['released']}")
        sub = result.get("above_floor")
        if sub:
            print(f"     where the line is his own median (n={sub['n']}): "
                  f"brier {sub['brier']} vs {sub['baseline_brier']}, "
                  f"acc {sub['accuracy']}, base rate {sub['base_rate']}")
        if result.get("failures"):
            print(f"     withheld because: {result['failures'][:3]}")

    report["_note"] = ("Walk-forward NBA backtest. Every scored season is one the "
                       "model never saw. Generated by scripts/nba_backtest.py -- "
                       "do not hand-edit.")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
