"""Run the six-season walk-forward backtest and write the release report."""
import json
import sys
from pathlib import Path

from nfl import backtest, config, data, features

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data-raw" / "nfl" / "backtest_report.json"


def main():
    player_weeks = data.player_weeks()
    games = data.games()
    report = {
        "_note": ("Walk-forward NFL prop backtest. Every scored season is one the "
                  "model never saw. Generated by scripts/nfl_backtest.py -- do not "
                  "hand-edit."),
        "seasons": list(config.SEASONS),
        "burn_in_seasons": config.BURN_IN_SEASONS,
        "line_definition": ("player's own entering MEDIAN for yardage markets, so "
                            "'over' means a better day than his typical one. Not a "
                            "sportsbook line -- no price is available here."),
        "markets": {},
    }
    for market in config.MARKETS:
        frame = features.build(player_weeks, market, games=games)
        result = backtest.evaluate(backtest.walk_forward(frame, market), market)
        report["markets"][market] = result
        o = result.get("overall", {})
        print(f"{market:20s} n={o.get('n'):6}  Brier {o.get('brier')} vs "
              f"{o.get('baseline_brier')}  ECE {o.get('ece')}  "
              f"RELEASED={result['released']}")
        if not result["released"]:
            print(f"    withheld: {result['reason'][:170]}")
    report["released_markets"] = sorted(m for m, r in report["markets"].items()
                                        if r.get("released"))
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(f"\nreleased: {report['released_markets'] or 'NONE'}")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
