"""Snapshot every current NFL roster from API-NFL.

WHY THIS IS NEEDED BEFORE WEEK 1. nflverse gives box scores, so a player's club is
inferred from where he last APPEARED -- which through the offseason means where he
played last December. The board says so in its own caveat, but a caveat is not a
fix: the 2026 season kicks off on 10 September with real movement behind it
(Kyler Murray to Minnesota, Tua Tagovailoa to Atlanta, Kenneth Walker III to
Kansas City, Mike Evans to San Francisco, among others). A projection attached to
the wrong club is worse than no projection, because it looks exactly as confident
as a correct one.

THE SAME DISCIPLINE THE SOCCER ROSTERS USE, and for the same reason it was learned
there: the snapshot CORROBORATES, it does not convict. Where a team's roster comes
back complete it is authoritative and reassigns a player's club. Where it comes
back THIN -- a failed fetch, a partial response -- the previous attribution is
kept and the gap is recorded, because absence from incomplete evidence is not
evidence of absence. Treating thin rosters as proof once deleted 70% of La Liga.

32 requests, one per team, on an allowance of 7,500.
"""
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

from nfl import api

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data-raw" / "nfl" / "rosters.json"
SEASON = 2026

# Below this a roster is not believable as a full NFL squad (53 active, 90 in
# camp). A team returning eight players is a broken fetch, not a small team, and
# must never be read as "everyone else has left".
MIN_CREDIBLE_ROSTER = 30


def main():
    if not api.available():
        if api.breaker_tripped():
            print("API-NFL allowance already spent today; keeping the existing "
                  "roster snapshot and using no quota")
        else:
            print("API_NFL_KEY is not set; skipping the roster sync")
        return 0

    # Paginated, so the budget must allow several pages per team rather than one.
    client = api.Client(budget=200)
    try:
        teams = client.get("teams", league=1, season=SEASON)
    except api.QuotaExhausted as exc:
        print(f"API-NFL allowance gone ({exc}); keeping the existing snapshot")
        return 0
    except Exception as exc:
        print(f"WARNING: could not list teams ({exc}); keeping the existing snapshot")
        return 0

    rosters, thin, failed = {}, [], []
    for team in teams:
        info = team.get("team") if isinstance(team.get("team"), dict) else team
        team_id = info.get("id")
        code = info.get("code") or info.get("abbreviation") or info.get("name")
        if not team_id or not code:
            continue
        try:
            rows = client.get_all("players", team=team_id, season=SEASON)
        except api.QuotaExhausted as exc:
            print(f"  stopped early: {exc}")
            break
        except Exception as exc:
            failed.append(f"{code}: {exc}")
            continue
        names = sorted({(r.get("name") or "").strip() for r in rows if r.get("name")})
        if len(names) < MIN_CREDIBLE_ROSTER:
            # Recorded, not trusted. See the module docstring.
            thin.append(f"{code} ({len(names)})")
        rosters[code] = {"players": names, "count": len(names),
                         "complete": len(names) >= MIN_CREDIBLE_ROSTER}

    payload = {
        "_note": ("Current NFL rosters from API-NFL, one request per team. "
                  "Generated by scripts/sync_nfl_rosters.py -- do not hand-edit. "
                  "A team marked complete=false is a THIN fetch and is NOT "
                  "authoritative: absence from it means unknown, never departed."),
        "updated": datetime.now(timezone.utc).isoformat(),
        "season": SEASON,
        "teams": rosters,
        "thin_rosters": thin,
        "failed_teams": failed,
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    tmp = OUT.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    tmp.replace(OUT)

    complete = sum(1 for v in rosters.values() if v["complete"])
    print(f"rosters: {len(rosters)} teams, {complete} complete"
          + (f", THIN: {', '.join(thin)}" if thin else "")
          + (f", failed: {len(failed)}" if failed else ""))
    print(client.report())
    return 0


if __name__ == "__main__":
    sys.exit(main())
