"""Fetch book prices for the upcoming slate. bet365 first, as asked.

ONE REQUEST PER UNPLAYED GAME, so a 16-game week costs 16 calls plus one to list
fixtures -- trivial against 7,500. It writes prices only; the edge is computed at
publish time so the number on the card always comes from the model and the price
that were current together.

AS OF 2026-08-27 THIS RETURNS NOTHING. The API lists Bet365 among its bookmakers
and defines 185 player-prop bet types, but no NFL fixture has prices posted: week
1 is 14 days out and both the bet365 query and the all-books query come back
empty, and the endpoint rejects league, season and date filters so there is no way
to ask it for whatever it does hold. That is "the books have not posted yet", not
"this API has no odds", and the two need different responses -- so this script
runs, reports honestly that it found nothing, and changes no file rather than
writing an empty one over a good one.
"""
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

from nfl import api, config, data, odds, publish

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data-raw" / "nfl" / "odds.json"
BET365_ID = 4


def upcoming_ids(client, upcoming) -> dict:
    """(home, away) -> API game id, for the fixtures we are about to price."""
    try:
        fixtures = client.get("games", league=1, season=config.CURRENT_SEASON)
    except Exception as exc:
        print(f"WARNING: could not list fixtures ({exc})")
        return {}
    wanted = {(r["home_team"], r["away_team"]) for _, r in upcoming.iterrows()}
    found = {}
    for row in fixtures:
        game = row.get("game") if isinstance(row.get("game"), dict) else row
        teams = row.get("teams") or {}
        home = ((teams.get("home") or {}).get("name")
                or (teams.get("home") or {}).get("code"))
        away = ((teams.get("away") or {}).get("name")
                or (teams.get("away") or {}).get("code"))
        for key in wanted:
            if home and away and key[0] in str(home) and key[1] in str(away):
                found[key] = game.get("id")
    return found


def main():
    if not api.available():
        if api.breaker_tripped():
            print("API-NFL allowance already spent today; keeping existing odds")
        else:
            print("API_NFL_KEY is not set; skipping the odds sync")
        return 0

    schedule = pd.concat([data.games(), data.games(seasons=(config.CURRENT_SEASON,))],
                         ignore_index=True)
    upcoming = publish.upcoming_games(schedule)
    if upcoming.empty:
        print("no upcoming slate; nothing to price")
        return 0

    client = api.Client(budget=40)
    ids = upcoming_ids(client, upcoming)
    print(f"matched {len(ids)} of {len(upcoming)} fixtures to API game ids")

    priced, unpriced = {}, 0
    for (home, away), gid in ids.items():
        try:
            rows = client.get("odds", game=gid, bookmaker=BET365_ID) \
                or client.get("odds", game=gid)
        except api.QuotaExhausted as exc:
            print(f"  stopped early: {exc}")
            break
        except Exception as exc:
            print(f"  {home} v {away}: {exc}")
            continue
        if not rows:
            unpriced += 1
            continue
        book = odds.pick_bookmaker(rows[0].get("bookmakers") or [])
        line = odds.moneyline(book, home, away)
        if not line:
            # Recognised nothing usable. Counted, never coerced -- a silent zero
            # would read as "the book thinks this is impossible" and manufacture
            # an enormous false edge.
            unpriced += 1
            continue
        priced[f"{home}|{away}"] = line

    if not priced:
        print(f"no prices available yet ({unpriced} fixture(s) returned none). "
              f"Leaving the existing file untouched.")
        print(client.report())
        return 0

    payload = {
        "_note": ("Book prices for the upcoming slate, de-vigged. Generated by "
                  "scripts/sync_nfl_odds.py -- do not hand-edit. Probabilities "
                  "here are FAIR (vig removed); raw_* are as quoted."),
        "updated": datetime.now(timezone.utc).isoformat(),
        "preferred_books": list(odds.PREFERRED_BOOKS),
        "games": priced,
        "unpriced": unpriced,
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    tmp = OUT.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    tmp.replace(OUT)
    books = sorted({v["book"] for v in priced.values() if v.get("book")})
    print(f"priced {len(priced)} fixture(s) from {books}; {unpriced} unpriced")
    print(client.report())
    return 0


if __name__ == "__main__":
    sys.exit(main())
