"""Pull the current NFL injury report from API-NFL.

WHY THIS CLOSES A REAL HOLE. The board's own caveat said it: "No injury data. A
ruled-out player is projected exactly as if fit." That is the single worst thing
a prop board can do -- a receiver who will not dress carries the same projection
as one who will, and his last five games look excellent right up until he is
inactive. nflverse publishes box scores, not availability, so this needs the API.

CHEAP ON PURPOSE. One request per team, 32 a day, against an allowance in the
thousands. The nflverse backfill deliberately does not touch this key; the key is
for the things only it knows, and availability is exactly that.

DEGRADES, NEVER BLOCKS. No key, a spent allowance, or a failed fetch leaves the
previous file in place and says so. A board without today's injury report is
worse than one with it and far better than no board.
"""
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

from nfl import api

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data-raw" / "nfl" / "injuries.json"
SEASON = 2026

# What we treat as "will not play". API-NFL's status strings vary by source, so
# match on substrings rather than an exact set -- a new spelling of "Doubtful"
# must not silently become "fit".
OUT_STATUSES = ("out", "injured reserve", "ir", "pup", "suspended",
                "did not play", "inactive")
DOUBT_STATUSES = ("doubtful", "questionable", "limited")


def classify(status: str) -> str:
    text = (status or "").strip().lower()
    if any(token in text for token in OUT_STATUSES):
        return "out"
    if any(token in text for token in DOUBT_STATUSES):
        return "doubt"
    return "fit"


def main():
    if not api.available():
        if api.breaker_tripped():
            print("API-NFL daily allowance already spent today; keeping the "
                  "existing injury file and using no quota")
        else:
            print("API_NFL_KEY is not set; skipping the injury sync")
        return 0

    client = api.Client(budget=40)
    try:
        teams = client.get("teams", league=1, season=SEASON)
    except api.QuotaExhausted as exc:
        print(f"API-NFL allowance gone ({exc}); keeping the existing injury file")
        return 0
    except Exception as exc:
        print(f"WARNING: could not list teams ({exc}); keeping the existing file")
        return 0

    report, failures = {}, []
    for team in teams:
        info = team.get("team") if isinstance(team.get("team"), dict) else team
        team_id, name = info.get("id"), info.get("code") or info.get("name")
        if not team_id:
            continue
        try:
            rows = client.get("injuries", team=team_id)
        except api.QuotaExhausted as exc:
            print(f"  stopped early: {exc}")
            break
        except Exception as exc:
            failures.append(f"{name}: {exc}")
            continue
        for row in rows:
            player = (row.get("player") or {})
            name_text = player.get("name")
            if not name_text:
                continue
            status = classify(row.get("status") or (row.get("injury") or {}).get("status"))
            if status == "fit":
                continue
            report.setdefault(name_text, {
                "status": status,
                "team": name,
                "detail": (row.get("description")
                           or (row.get("injury") or {}).get("type") or ""),
            })

    payload = {
        "_note": ("Current NFL availability from API-NFL, one request per team. "
                  "Generated by scripts/sync_nfl_injuries.py -- do not hand-edit. "
                  "Absence from this file means NOT REPORTED, which is not the "
                  "same as confirmed fit."),
        "updated": datetime.now(timezone.utc).isoformat(),
        "season": SEASON,
        "players": report,
        "teams_failed": failures,
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    tmp = OUT.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    tmp.replace(OUT)

    counts = {}
    for entry in report.values():
        counts[entry["status"]] = counts.get(entry["status"], 0) + 1
    print(f"injury report: {counts or 'nobody listed'}"
          + (f"; {len(failures)} team(s) failed" if failures else ""))
    print(client.report())
    return 0


if __name__ == "__main__":
    sys.exit(main())
