"""Run the Champions League walk-forward backtest and write the report."""
import json
import sys
from pathlib import Path

from ucl import backtest, data

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data-raw" / "ucl" / "backtest_report.json"


def main():
    frame = data.matches()
    if frame.empty:
        print("no cached history; run scripts.sync_ucl_history first")
        return 0
    result = backtest.evaluate(backtest.walk_forward(frame))
    result["_note"] = ("Walk-forward Champions League backtest. Every scored "
                       "season is one the model never saw. Generated by "
                       "scripts/ucl_backtest.py -- do not hand-edit.")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")

    overall = result.get("overall", {})
    print(f"n={overall.get('n')}  RPS {overall.get('rps')} vs baseline "
          f"{overall.get('rps_baseline')}  accuracy {overall.get('accuracy')}  "
          f"RELEASED={result['released']}")
    for era, stats in (result.get("eras") or {}).items():
        if stats:
            print(f"  {era:20s} n={stats['n']:5d}  RPS {stats['rps']} "
                  f"vs {stats['rps_baseline']}")
    print(f"skipped for no history: {result.get('skipped_no_history')}")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
